package com.cometchat.uikit.kotlin.shared.spans

import android.text.SpannableStringBuilder
import android.text.Spanned
import com.cometchat.uikit.kotlin.shared.formatters.style.PromptTextStyle
import io.kotest.matchers.shouldBe
import io.kotest.property.Arb
import io.kotest.property.arbitrary.arbitrary
import io.kotest.property.arbitrary.char
import io.kotest.property.arbitrary.int
import io.kotest.property.arbitrary.string
import io.kotest.property.checkAll
import kotlinx.coroutines.runBlocking
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Property-based tests for [MentionCodeBlockHandler.consumeMentionsInRange] and
 * [MentionCodeBlockHandler.restoreMentionsInRange] round-trip behaviour.
 *
 * Feature: v6-rich-text-composer, Property 10: Mention consume/restore round-trip
 *
 * **Validates: Requirements 14.1, 14.2**
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [28], manifest = Config.NONE)
class MentionConsumeRestorePropertyTest {

    /**
     * Describes a mention span to place on the Editable before the round-trip.
     */
    data class MentionDef(
        val id: Char,
        val text: String,
        val start: Int,
        val end: Int,
        val color: Int
    )

    /**
     * Full test case: base text with non-overlapping mention spans.
     */
    data class MentionTestCase(
        val baseText: String,
        val mentions: List<MentionDef>
    )

    /**
     * Generator for a non-null, non-zero Char id (NonEditableSpan id).
     * Avoids '\u0000' which makes canRestore() return false.
     */
    private val arbIdChar: Arb<Char> = Arb.char('!' .. '~')

    /**
     * Generator for a random color int (used for PromptTextStyle).
     */
    private val arbColor: Arb<Int> = Arb.int(0x010000..0xFFFFFF)

    /**
     * Generates a [MentionTestCase] with random base text (1-100 chars) and
     * 1-5 non-overlapping mention spans placed at valid positions.
     *
     * Mentions are generated by picking random non-overlapping sub-ranges of
     * the base text. Each mention has a random id char and random text content.
     */
    private val arbTestCase: Arb<MentionTestCase> = arbitrary {
        val baseText = Arb.string(minSize = 5, maxSize = 100).bind()
        val len = baseText.length
        val mentionCount = Arb.int(1..minOf(5, len / 2)).bind()

        // Generate non-overlapping ranges by picking random gap-separated positions
        val mentions = mutableListOf<MentionDef>()
        var cursor = 0
        for (i in 0 until mentionCount) {
            val remaining = len - cursor
            // Need at least 1 char for this mention
            if (remaining < 1) break
            val start = Arb.int(cursor..minOf(cursor + remaining / (mentionCount - i + 1), len - 1)).bind()
            val maxEnd = minOf(start + 10, len) // cap mention length at 10
            if (start >= maxEnd) break
            val end = Arb.int(start + 1..maxEnd).bind()

            val id = arbIdChar.bind()
            val mentionText = Arb.string(minSize = 1, maxSize = 8).bind()
            val color = arbColor.bind()
            mentions.add(MentionDef(id, mentionText, start, end, color))
            cursor = end // next mention starts after this one
        }

        MentionTestCase(baseText, mentions)
    }

    /**
     * Property 10: Mention consume/restore round-trip.
     *
     * For any Editable containing NonEditableSpan mention spans, calling
     * consumeMentionsInRange() followed by restoreMentionsInRange() on the
     * same range SHALL produce an Editable where each original NonEditableSpan
     * is restored with identical id, text, and textAppearance values, and
     * span positions are preserved.
     *
     * **Validates: Requirements 14.1, 14.2**
     */
    @Test
    fun `Property 10 - consume then restore round-trip preserves mention id, text, textAppearance and positions`() {
        runBlocking {
            checkAll(100, arbTestCase) { tc ->
                val editable = SpannableStringBuilder(tc.baseText)

                // Record original mention data for later comparison
                data class OriginalMention(
                    val id: Char,
                    val text: String,
                    val textAppearance: PromptTextStyle?,
                    val start: Int,
                    val end: Int
                )

                val originals = mutableListOf<OriginalMention>()

                // Place NonEditableSpan mentions on the editable
                for (m in tc.mentions) {
                    val style = PromptTextStyle().setColor(m.color)
                    val span = NonEditableSpan(m.id, m.text, style)
                    editable.setSpan(span, m.start, m.end, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
                    originals.add(OriginalMention(m.id, m.text, style, m.start, m.end))
                }

                // Consume all mentions in the full range
                MentionCodeBlockHandler.consumeMentionsInRange(editable, 0, editable.length)

                // Verify all NonEditableSpans are gone and replaced by ConsumedMentionSpans
                val nonEditableAfterConsume = editable.getSpans(0, editable.length, NonEditableSpan::class.java)
                nonEditableAfterConsume.size shouldBe 0

                val consumedSpans = editable.getSpans(0, editable.length, ConsumedMentionSpan::class.java)
                consumedSpans.size shouldBe originals.size

                // Restore all mentions in the full range
                MentionCodeBlockHandler.restoreMentionsInRange(editable, 0, editable.length)

                // Verify all ConsumedMentionSpans are gone
                val consumedAfterRestore = editable.getSpans(0, editable.length, ConsumedMentionSpan::class.java)
                consumedAfterRestore.size shouldBe 0

                // Verify restored NonEditableSpans match originals
                val restored = editable.getSpans(0, editable.length, NonEditableSpan::class.java)
                restored.size shouldBe originals.size

                // Sort both by start position for stable comparison
                val restoredSorted = restored.sortedBy { editable.getSpanStart(it) }
                val originalsSorted = originals.sortedBy { it.start }

                for (i in restoredSorted.indices) {
                    val r = restoredSorted[i]
                    val o = originalsSorted[i]

                    r.getId() shouldBe o.id
                    r.getText() shouldBe o.text
                    r.getTextAppearance() shouldBe o.textAppearance
                    editable.getSpanStart(r) shouldBe o.start
                    editable.getSpanEnd(r) shouldBe o.end
                }
            }
        }
    }
}
